### ISSUE TITLE
systemd-cryptenroll command issue

### ISSUE THREAD

**Issue by finnhagard** [joelmathewthomas/archinstall-luks2-lvm2-secureboot-tpm2#1]
running `sudo systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7 --tpm2-public-key /etc/kernel/pcr-initrd.pub.pem --tpm2-with-pin=true /dev/nvme0n1p2`

it says that `--tpm2-with-pin` isn't a valid option, I just ran without it, but I'd still be interested in fixing it.

also is it supposed to prompt for a decryption password on boot?

**Comment by jasonanovak** [comment]
If you want to be prompted for a pin on boot, you need to run the command with:
--tpm2-with-pin=true

The BOOL in documentation is meant to be substituted with true or false depending on user preference.

**Comment by finnhagard** [comment]
I tried `--tpm2-with-pin=true` and it didn't work, same error.

**Comment by joelmathewthomas** [comment]
> I tried `--tpm2-with-pin=true` and it didn't work, same error.

Use TRUE instead of true

**Comment by finnhagard** [comment]
> > I tried `--tpm2-with-pin=true` and it didn't work, same error.
> 
> Use TRUE instead of true

Is there a way to do this post-install without wiping? Thought I tried that too.

**Comment by joelmathewthomas** [comment]
> > > I tried `--tpm2-with-pin=true` and it didn't work, same error.
> > 
> > Use TRUE instead of true
> 
> Is there a way to do this post-install without wiping? Thought I tried that too.

You can do this without changing anything. I assume you currently have done all the steps up until secure boot. Make sure the output of bootctl status shows secure boot as enabled. If it's okay so far, you can just continue doing the rest of the steps .

**Comment by finnhagard** [comment]
> > > > I tried `--tpm2-with-pin=true` and it didn't work, same error.
> > > 
> > > 
> > > Use TRUE instead of true
> > 
> > 
> > Is there a way to do this post-install without wiping? Thought I tried that too.
> 
> You can do this without changing anything. I assume you currently have done all the steps up until secure boot. Make sure the output of bootctl status shows secure boot as enabled. If it's okay so far, you can just continue doing the rest of the steps .

TRUE seemed to work, on boot it now asks for the PIN and a passphrase, is this correct (before it was just a passphrase)?

**Comment by joelmathewthomas** [comment]
> > > > > I tried `--tpm2-with-pin=true` and it didn't work, same error.
> > > > 
> > > > 
> > > > Use TRUE instead of true
> > > 
> > > 
> > > Is there a way to do this post-install without wiping? Thought I tried that too.
> > 
> > You can do this without changing anything. I assume you currently have done all the steps up until secure boot. Make sure the output of bootctl status shows secure boot as enabled. If it's okay so far, you can just continue doing the rest of the steps .
> 
> TRUE seemed to work, on boot it now asks for the PIN and a passphrase, is this correct (before it was just a passphrase)?

That's how it works. You use the pin to unlock the Tpm. But it should only ask for the pin. Once you enter the pin, the Tpm should automatically release the passphrase. So if you're being asked both, either you entered the pin incorrectly or something must have changed , such as the secure boot state or your UEFI firmware, in which case you must redo the process referring to the [tips](https://github.com/joelmathewthomas/archinstall-luks2-lvm2-secureboot-tpm2?tab=readme-ov-file#17-tips) section in the guide .

**Comment by finnhagard** [comment]
> > > > > > I tried `--tpm2-with-pin=true` and it didn't work, same error.
> > > > > 
> > > > > 
> > > > > Use TRUE instead of true
> > > > 
> > > > 
> > > > Is there a way to do this post-install without wiping? Thought I tried that too.
> > > 
> > > 
> > > You can do this without changing anything. I assume you currently have done all the steps up until secure boot. Make sure the output of bootctl status shows secure boot as enabled. If it's okay so far, you can just continue doing the rest of the steps .
> > 
> > 
> > TRUE seemed to work, on boot it now asks for the PIN and a passphrase, is this correct (before it was just a passphrase)?
> 
> That's how it works. You use the pin to unlock the Tpm. But it should only ask for the pin. Once you enter the pin, the Tpm should automatically release the passphrase. So if you're being asked both, either you entered the pin incorrectly or something must have changed , such as the secure boot state or your UEFI firmware, in which case you must redo the process referring to the [tips](https://github.com/joelmathewthomas/archinstall-luks2-lvm2-secureboot-tpm2?tab=readme-ov-file#17-tips) section in the guide .

Haven't changed any settings. To be more clear when I setup everything up since that flag wasn't working I just ignored it and continued with the guide after I set it up without the flag I was being prompted for the passphrase, now after adding the flag and re-running the command I now have to enter the pin and passphrase.

**Comment by joelmathewthomas** [comment]
> > > > > > > I tried `--tpm2-with-pin=true` and it didn't work, same error.
> > > > > > 
> > > > > > 
> > > > > > Use TRUE instead of true
> > > > > 
> > > > > 
> > > > > Is there a way to do this post-install without wiping? Thought I tried that too.
> > > > 
> > > > 
> > > > You can do this without changing anything. I assume you currently have done all the steps up until secure boot. Make sure the output of bootctl status shows secure boot as enabled. If it's okay so far, you can just continue doing the rest of the steps .
> > > 
> > > 
> > > TRUE seemed to work, on boot it now asks for the PIN and a passphrase, is this correct (before it was just a passphrase)?
> > 
> > That's how it works. You use the pin to unlock the Tpm. But it should only ask for the pin. Once you enter the pin, the Tpm should automatically release the passphrase. So if you're being asked both, either you entered the pin incorrectly or something must have changed , such as the secure boot state or your UEFI firmware, in which case you must redo the process referring to the [tips](https://github.com/joelmathewthomas/archinstall-luks2-lvm2-secureboot-tpm2?tab=readme-ov-file#17-tips) section in the guide .
> 
> Haven't changed any settings. To be more clear when I setup everything up since that flag wasn't working I just ignored it and continued with the guide after I set it up without the flag I was being prompted for the passphrase, now after adding the flag and re-running the command I now have to enter the pin and passphrase.

In that case , the Tpm should have autounlocked, not promoted you for a passphrase. 

Using the tips section as reference, wipe existing tokens and redo the whole process.

Its working properly only if it prompts you for a pin and continues to boot.

**Comment by finnhagard** [comment]
> > > > > > > > I tried `--tpm2-with-pin=true` and it didn't work, same error.
> > > > > > > 
> > > > > > > 
> > > > > > > Use TRUE instead of true
> > > > > > 
> > > > > > 
> > > > > > Is there a way to do this post-install without wiping? Thought I tried that too.
> > > > > 
> > > > > 
> > > > > You can do this without changing anything. I assume you currently have done all the steps up until secure boot. Make sure the output of bootctl status shows secure boot as enabled. If it's okay so far, you can just continue doing the rest of the steps .
> > > > 
> > > > 
> > > > TRUE seemed to work, on boot it now asks for the PIN and a passphrase, is this correct (before it was just a passphrase)?
> > > 
> > > 
> > > That's how it works. You use the pin to unlock the Tpm. But it should only ask for the pin. Once you enter the pin, the Tpm should automatically release the passphrase. So if you're being asked both, either you entered the pin incorrectly or something must have changed , such as the secure boot state or your UEFI firmware, in which case you must redo the process referring to the [tips](https://github.com/joelmathewthomas/archinstall-luks2-lvm2-secureboot-tpm2?tab=readme-ov-file#17-tips) section in the guide .
> > 
> > 
> > Haven't changed any settings. To be more clear when I setup everything up since that flag wasn't working I just ignored it and continued with the guide after I set it up without the flag I was being prompted for the passphrase, now after adding the flag and re-running the command I now have to enter the pin and passphrase.
> 
> In that case , the Tpm should have autounlocked, not promoted you for a passphrase.
> 
> Using the tips section as reference, wipe existing tokens and redo the whole process.
> 
> Its working properly only if it prompts you for a pin and continues to boot.

Seemed to work, thank you so much. :)

**Comment by joelmathewthomas** [comment]
> > > > > > > > > I tried `--tpm2-with-pin=true` and it didn't work, same error.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Use TRUE instead of true
> > > > > > > 
> > > > > > > 
> > > > > > > Is there a way to do this post-install without wiping? Thought I tried that too.
> > > > > > 
> > > > > > 
> > > > > > You can do this without changing anything. I assume you currently have done all the steps up until secure boot. Make sure the output of bootctl status shows secure boot as enabled. If it's okay so far, you can just continue doing the rest of the steps .
> > > > > 
> > > > > 
> > > > > TRUE seemed to work, on boot it now asks for the PIN and a passphrase, is this correct (before it was just a passphrase)?
> > > > 
> > > > 
> > > > That's how it works. You use the pin to unlock the Tpm. But it should only ask for the pin. Once you enter the pin, the Tpm should automatically release the passphrase. So if you're being asked both, either you entered the pin incorrectly or something must have changed , such as the secure boot state or your UEFI firmware, in which case you must redo the process referring to the [tips](https://github.com/joelmathewthomas/archinstall-luks2-lvm2-secureboot-tpm2?tab=readme-ov-file#17-tips) section in the guide .
> > > 
> > > 
> > > Haven't changed any settings. To be more clear when I setup everything up since that flag wasn't working I just ignored it and continued with the guide after I set it up without the flag I was being prompted for the passphrase, now after adding the flag and re-running the command I now have to enter the pin and passphrase.
> > 
> > In that case , the Tpm should have autounlocked, not promoted you for a passphrase.
> > 
> > Using the tips section as reference, wipe existing tokens and redo the whole process.
> > 
> > Its working properly only if it prompts you for a pin and continues to boot.
> 
> Seemed to work, thank you so much. :)

Glad to know my guide helped you.
